export default {
  loan_application_id: "los/source_system_id",
  salesperson_first_name: "loan_officer/employee_sales_agent_firstname",
  salesperson_last_name: "loan_officer/employee_sales_agent_lastname",
  salesperson_email_address: "loan_officer/employee_sales_agent_emailaddress",
  processing_fee: "los/transaction_structure_processing_price",
  funding_date: "los/funding_date",
  lienholder_name: "los/lien_holder_id",
  vin: "los/vehicle_vin",
  customer_id: "borrower/internal_caribou_id",
  customer_email: "borrower/email",
  customer_first_name: "borrower/firstname",
  customer_last_name: "borrower/lastname",
  lead_source: "los/lead_source",
  phone_number: "borrower/phone",
  address_1: "borrower/addressbook/addr1",
  address_2: "borrower/addressbook/addr2",
  city: "borrower/addressbook/city",
  state: "borrower/addressbook/state",
  zip: "borrower/addressbook/zip",
  short_funding: "los/transaction_structure_short_fund_price",
  lender_surcharge: "los/transaction_structure_lender_surcharge_price",
  maestro_lender_id: "los/lender_unique_code",
  lender_loan_id: "los/lender_loan_id",
  lienholder_account_number: "los/lien_holder_location_acct_num",
  dmv_fee: "los/transaction_structure_dmv_price",
  lienholder_per_diem: "los/lien_holder_per_diem",
  lienholder_payoff_good_until_date: "los/lien_holder_payoff_good_until_date",
  lienholder_payoff_amount: "los/transaction_structure_loan_payoff_amount",
  gap_term: "los/transaction_structure_gap_term",
  fico: "los/fico_no",
  vsc_cost: "los/transaction_structure_vehicle_service_contract_cost",
  vsc_price: "los/transaction_structure_vehicle_service_contract_price",
  vsc_contract_number: "los/transaction_structure_vehicle_service_contract_no",
  vsc_provider: "los/transaction_structure_vehicle_service_contract_vdr",
  gap_cost: "los/transaction_structure_gap_cost",
  gap_price: "los/transaction_structure_gap_price",
  gap_provider: "los/transaction_structure_gap_vdr",
  gap_contract_number: "los/transaction_structure_gap_no",
  key_replacement_price: "los/transaction_structure_key_replacement_price",
  key_replacement_cost: "los/transaction_structure_key_replacement_cost",
  key_replacement_provider: "los/transaction_structure_key_replacement_vdr",
  key_replacement_contract_number:
    "los/transaction_structure_key_replacement_no",
  cosmetic_package_price: "los/transaction_structure_cosmetic_care_price",
  cosmetic_package_cost: "los/transaction_structure_cosmetic_care_cost",
  cosmetic_package_provider: "los/transaction_structure_cosmetic_care_vdr",
  cosmetic_package_contract_number:
    "los/transaction_structure_cosmetic_care_no",
  lender_loan_number: "los/lender_loan_id",
  coversheet_finalization_date: "los/coversheet_finalization_date",
  origination_percentage: "los/transaction_structure_origination_pct",
  origination_fee: "los/transaction_structure_origination_price",
  total_amount_financed: "los/total_amount_financed",
}
